[tool.poetry]
name = "genesis backend"
version = "alpha 1.0"
description = ""
authors = ["Luis Maia & Gabriel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
