[tool.poetry]
name = "genesis ds"
version = "0.1.0"
description = ""
authors = ["Luis Maia & Gabriel Miranda"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
